import type { SheetData } from './types';

export const mockTimetableData: SheetData = [
  [
    { value: 'Day', style: { bold: true, backgroundColor: '#d9ead3' } },
    { value: 'Classroom No.', style: { bold: true, backgroundColor: '#d9ead3' } },
    { value: 'time', style: { bold: true, backgroundColor: '#d9ead3' }, colSpan: 10 },
  ],
  [
    { value: 'Day, Date', style: { bold: true } },
    { value: 'Classroom No.', style: { bold: true } },
    { value: '09:00 am - 10:15 am', style: { bold: true } },
    { value: '10:30 am - 11:45 am', style: { bold: true } },
    { value: '12 noon - 1:15 pm', style: { bold: true } },
    { value: '(Lunch)', style: { bold: true } },
    { value: '2:30 pm - 3:45 pm', style: { bold: true } },
    { value: '4:00 pm - 5:15 pm', style: { bold: true } },
    { value: '5:30 pm - 6:45 pm', style: { bold: true } },
    { value: '7:00 pm - 8:15 pm', style: { bold: true } },
    { value: '8:45 pm - 10:00 pm', style: { bold: true } },
    { value: '10:15 pm - 11:30 pm', style: { bold: true } },
  ],
  [
    { value: 'Tuesday, September 16, 2025' },
    { value: 'F-201', style: { color: '#ff8c00' } },
    { value: 'Registration' },
    { value: '' },
    { value: 'IMC 1', style: { backgroundColor: '#4dd0e1' } },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: 'LRM B 1', style: { backgroundColor: '#aed581' } },
    { value: 'MBA 1' },
    { value: 'MPPP B 1', style: { color: 'red' } },
    { value: 'MPPP A 1', style: { color: 'red' } },
    { value: 'AINLP 1', style: { backgroundColor: '#4dd0e1' } },
    { value: '', style: { backgroundColor: '#00ff00' } },
  ],
  [
    { value: 'Tuesday, September 16, 2025' },
    { value: 'F-203', style: { color: '#ff8c00' } },
    { value: 'CG A 1', style: { backgroundColor: '#aed581' } },
    { value: 'CG B 1', style: { backgroundColor: '#aed581' } },
    { value: 'LRM A 1' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: 'Sport A 1' },
    { value: 'Sport B 1' },
    { value: 'EPP A 1' },
    { value: 'EPP B 1' },
    { value: '' },
    { value: '', style: { backgroundColor: '#00ff00' } },
  ],
  [
    { value: 'Tuesday, September 16, 2025' },
    { value: 'F-103', style: { color: '#ff8c00' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: '' },
    { value: '' },
    { value: 'CFA 1' },
    { value: '' },
    { value: '' },
    { value: '', style: { backgroundColor: '#00ff00' } },
  ],
  [
    { value: 'Tuesday, September 16, 2025' },
    { value: 'SRC-201', style: { color: '#ff8c00' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '', style: { backgroundColor: '#00ff00' } },
  ],
  [
    { value: 'Tuesday, September 16, 2025' },
    { value: 'G103', style: { color: '#ff8c00' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '', style: { backgroundColor: '#00ff00' } },
  ],
  [
    { value: 'Wednesday, September 17, 2025' },
    { value: 'F-201', style: { color: '#ff8c00' } },
    { value: 'LRM B 2', style: { backgroundColor: '#aed581' } },
    { value: 'LRM A 2' },
    { value: 'Sport A 2' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: 'Sport B 2' },
    { value: 'IMC 2', style: { backgroundColor: '#4dd0e1' } },
    { value: 'MPPP B 2', style: { color: 'red' } },
    { value: 'MPPP A 2', style: { color: 'red' } },
    { value: '', style: { backgroundColor: '#00ff00' } },
    { value: '', style: { backgroundColor: '#00ff00' } },
  ],
  [
    { value: 'Wednesday, September 17, 2025' },
    { value: 'F-203', style: { color: '#ff8c00' } },
    { value: 'CG A 2', style: { backgroundColor: '#aed581' } },
    { value: 'CG B 2', style: { backgroundColor: '#aed581' } },
    { value: '' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: 'SS N 1' },
    { value: 'SS Q 1' },
    { value: 'CFA 2' },
    { value: '' },
    { value: '' },
    { value: '', style: { backgroundColor: '#00ff00' } },
  ],
  [
    { value: 'Wednesday, September 17, 2025' },
    { value: 'F-103', style: { color: '#ff8c00' } },
    { value: '' },
    { value: 'SS M 1' },
    { value: '' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: '', style: { backgroundColor: '#00ff00' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: 'Wednesday, September 17, 2025' },
    { value: 'SRC-201', style: { color: '#ff8c00' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: 'Wednesday, September 17, 2025' },
    { value: 'G103', style: { color: '#ff8c00' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: 'Thursday, September 18, 2025' },
    { value: 'F-201', style: { color: '#ff8c00' } },
    { value: 'FMV A 1', style: { backgroundColor: '#aed581' } },
    { value: 'FMV B 1' },
    { value: 'Sport A 3' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: 'Sport B 3' },
    { value: 'MBA 2' },
    { value: 'EPP A 2' },
    { value: 'EPP B 2' },
    { value: 'SABE 1' },
    { value: '', style: { backgroundColor: '#00ff00' } },
  ],
  [
    { value: 'Thursday, September 18, 2025' },
    { value: 'F-203', style: { color: '#ff8c00' } },
    { value: 'IMC 3', style: { backgroundColor: '#4dd0e1' } },
    { value: 'Social A 1' },
    { value: 'Social B 1' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: 'PFWM A 1' },
    { value: 'PFWM B 1' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '', style: { backgroundColor: '#00ff00' } },
  ],
  [
    { value: 'Thursday, September 18, 2025' },
    { value: 'F-103', style: { color: '#ff8c00' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: 'Thursday, September 18, 2025' },
    { value: 'SRC-201', style: { color: '#ff8c00' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
  [
    { value: 'Thursday, September 18, 2025' },
    { value: 'G103', style: { color: '#ff8c00' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '', colSpan: 1, style: { borderRight: '1px solid #000' } },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
    { value: '' },
  ],
];

    